<h1>Practical Tasks<h1>

<h2>Import modules<h2>

In [1]:
import numpy as np

<h2>Task 1<h2>

In [14]:
# task 1
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [1, 6, 5], [0, 1, 0]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'U:\n{U}')
print(f'D:\n{D}')
print(f'V:\n{V}')
np.allclose(A, np.dot(U, np.dot(D, V.T)))

U:
[[-0.13379126 -0.15018982 -0.49897485 -0.58823211 -0.58823211 -0.13613587]
 [-0.28033189  0.54578921  0.64779129 -0.31772114 -0.31772114  0.04473443]
 [ 0.11537437  0.81693918 -0.54111922  0.10404268  0.10404268  0.0695655 ]
 [-0.66567551 -0.02407781 -0.12985909  0.63805203 -0.36194797 -0.03628032]
 [-0.66567551 -0.02407781 -0.12985909 -0.36194797  0.63805203 -0.03628032]
 [-0.06288809 -0.1049193  -0.06966888 -0.06398946 -0.06398946  0.98589755]]
D:
[[11.81584782  0.          0.        ]
 [ 0.          6.14510015  0.        ]
 [ 0.          0.          2.57361313]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
V:
[[-0.09470494  0.36654766 -0.92556674]
 [-0.74307611 -0.64473959 -0.17930075]
 [-0.66247179  0.67078587  0.33343284]]


True

In [17]:
# task 2
# eucledian norm
print(f'||A||_E = {D[0][0]} (eucledian norm: extract largest singular value from matrix D)')
print(f'||A||_E = {np.linalg.norm(A, ord=2)} (eucledian norm: largest singular value via numpy.linalg.norm)')

# frobenius norm
print(f'||A||_E = {np.sqrt(np.sum(np.square(s)))} (frobenius norm: using matrix D)')
print(f'||A||_E = {np.linalg.norm(A)} (frobenuis norm: numpy.linalg.norm)')


||A||_E = 11.815847815828706 (eucledian norm: extract largest singular value from matrix D)
||A||_E = 11.815847815828711 (eucledian norm: largest singular value via numpy.linalg.norm)
||A||_E = 13.564659966250534 (frobenius norm: using matrix D)
||A||_E = 13.564659966250536 (frobenuis norm: numpy.linalg.norm)
